library(methylKit)
file.list <- list("./split_cg_context/oPK1.CG_meth.txt",
                  "./split_cg_context/oPK2.CG_meth.txt",
                  "./split_cg_context/oPK3.CG_meth.txt",
                  "./split_cg_context/oPK4.CG_meth.txt",
                  "./split_cg_context/oPK5.CG_meth.txt",
                  "./split_cg_context/yPK1.CG_meth.txt",
                  "./split_cg_context/yPK2.CG_meth.txt",
                  "./split_cg_context/yPK3.CG_meth.txt",
                  "./split_cg_context/yPK4.CG_meth.txt",
                  "./split_cg_context/yPK5.CG_meth.txt")
sample.list <- list("All_OLD1_CG",
                    "All_OLD2_CG",
                    "All_OLD3_CG",
                    "All_OLD4_CG",
                    "All_OLD5_CG",
                    "All_YOUNG1_CG",
                    "All_YOUNG2_CG",
                    "All_YOUNG3_CG",
                    "All_YOUNG4_CG",
                    "All_YOUNG5_CG")
methData <- methRead(file.list,
                     sample.id=sample.list,
                     treatment=c(1, 1, 1, 1, 1,
                                 0, 0, 0, 0, 0),
                     assembly='Rs_genome',
                     header=TRUE,
                     context="CpG",
                     resolution="base",
                     skip=1,
                     pipeline=list(fraction=TRUE,
                                   chr.col=1,
                                   start.col=2,
                                   end.col=2,
                                   coverage.col=6,
                                   strand.col=3,
                                   freqC.col=5))
methData.filtered = filterByCoverage(methData,
                                     lo.count = 10,
                                     lo.perc=NULL,
                                     hi.count=NULL,
                                     hi.perc=99.9,
                                     save.db=TRUE,
                                     dbdir="./split_cg_context",
                                     dbtype="tabix")
Meth = unite(methData.filtered,
                 destrand=FALSE,
                 save.db=TRUE,
                 dbdir="./split_cg_context",
                 dbtype="tabix",
                 suffix="CG",
                 mc.cores=10)
Diff = calculateDiffMeth(Meth,
                         mc.cores=10,
                         save.db=TRUE,
                         dbdir="./split_cg_context",
                         dbtype="tabix",
                         suffix="CG")